#BUILD
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS builder

# Set the working directory inside the container
WORKDIR /ProjectGPIO

COPY ./ .


RUN dotnet restore && \
    dotnet add package System.Device.Gpio --version 2.2.0-* && \
    #dotnet build && \
    dotnet publish --runtime linux-arm64 --self-contained -o out

FROM mcr.microsoft.com/dotnet/aspnet:8.0.3-jammy-arm64v8 AS runtime

# Set the working directory inside the container
WORKDIR /ProjectGPIO
COPY --from=builder /ProjectGPIO/out ./

RUN apt-get update && \
    apt-get install -y \
    libgpiod2 \
    libgpiod-dev

# Make the binary executable
RUN chmod +x LightSwitch

# Command to run the executable
ENTRYPOINT ["./LightSwitch"]
